const specialtyMap = {
    "Allergy and Immunology": "ALLERGY_IMMUNOLOGY",
    "Anesthesiology": "ANESTHESIOLOGY",
    "Cardiology": "CARDIOLOGY",
    "Dermatology": "DERMATOLOGY",
    "Endocrinology": "ENDOCRINOLOGY",
    "Gastroenterology": "GASTROENTEROLOGY",
    "Geriatrics": "GERIATRICS",
    "Hematology": "HEMATOLOGY",
    "Infectious Disease": "INFECTIOUS_DISEASE",
    "Internal Medicine": "INTERNAL_MEDICINE",
    "Nephrology": "NEPHROLOGY",
    "Neurology": "NEUROLOGY",
    "Obstetrics and Gynecology": "OBSTETRICS_GYNECOLOGY",
    "Oncology": "ONCOLOGY",
    "Ophthalmology": "OPHTHALMOLOGY",
    "Orthopedics": "ORTHOPEDICS",
    "Otolaryngology (ENT)": "OTOLARYNGOLOGY",
    "Pediatrics": "PEDIATRICS",
    "Psychiatry": "PSYCHIATRY",
    "Pulmonology": "PULMONOLOGY",
    "Radiology": "RADIOLOGY",
    "Rheumatology": "RHEUMATOLOGY",
    " General - Surgery" :"SURGERY_GENERAL",
    " Cardiothoracic - Surgery": "SURGERY_CARDIOTHORACIC",
    " Neurosurgery - Surgery": "SURGERY_NEUROSURGERY",
    " Orthopedic - Surgery": "SURGERY_ORTHOPEDIC",
    " Plastic - Surgery": "SURGERY_PLASTIC",
    " Vascular - Surgery": "SURGERY_VASCULAR",
    "Urology": "UROLOGY",
  };
  