const specialityMap: { [key: string]: string } = {
    ALLERGY_IMMUNOLOGY: "Allergy and Immunology",
    ANESTHESIOLOGY: "Anesthesiology",
    CARDIOLOGY: "Cardiology",
    DERMATOLOGY: "Dermatology",
    ENDOCRINOLOGY: "Endocrinology",
    GASTROENTEROLOGY: "Gastroenterology",
    GERIATRICS: "Geriatrics",
    HEMATOLOGY: "Hematology",
    INFECTIOUS_DISEASE: "Infectious Disease",
    INTERNAL_MEDICINE: "Internal Medicine",
    NEPHROLOGY: "Nephrology",
    NEUROLOGY: "Neurology",
    OBSTETRICS_GYNECOLOGY: "Obstetrics and Gynecology",
    ONCOLOGY: "Oncology",
    OPHTHALMOLOGY: "Ophthalmology",
    ORTHOPEDICS: "Orthopedics",
    OTOLARYNGOLOGY: "Otolaryngology (ENT)",
    PEDIATRICS: "Pediatrics",
    PSYCHIATRY: "Psychiatry",
    PULMONOLOGY: "Pulmonology",
    RADIOLOGY: "Radiology",
    RHEUMATOLOGY: "Rheumatology",
    SURGERY_GENERAL: "General Surgery",
    SURGERY_CARDIOTHORACIC: "Cardiothoracic Surgery",
    SURGERY_NEUROSURGERY: "Neurosurgery",
    SURGERY_ORTHOPEDIC: "Orthopedic Surgery",
    SURGERY_PLASTIC: "Plastic Surgery",
    SURGERY_VASCULAR: "Vascular Surgery",
    UROLOGY: "Urology",
  };
